import { defineConfig } from 'oxlint';

export default defineConfig({
    ignorePatterns: ['coverage/*', 'data/*', 'dist/*', 'docker/*', 'node_modules/*', 'public/*'],
    plugins: ['eslint', 'typescript', 'unicorn', 'oxc', 'react', 'jsx-a11y', 'vitest'],
    settings: {
        react: {
            version: '19.2.8',
        },
    },
    rules: {
        'typescript/explicit-function-return-type': [
            'warn',
            {
                allowExpressions: true,
                allowTypedFunctionExpressions: true,
                allowHigherOrderFunctions: true,
                allowDirectConstAssertionInArrowFunctions: true,
                allowConciseArrowFunctionExpressionsStartingWithVoid: true,
                allowFunctionsWithoutTypeParameters: true,
            },
        ],
        'typescript/no-unused-expressions': 'error',
        'typescript/no-unused-vars': [
            'error',
            {
                vars: 'all',
                varsIgnorePattern: '^_',
                args: 'after-used',
                argsIgnorePattern: '^_',
                caughtErrors: 'all',
                caughtErrorsIgnorePattern: '^_',
                destructuredArrayIgnorePattern: '^_',
            },
        ],
        'typescript/consistent-type-assertions': ['error', { assertionStyle: 'as' }],
        'typescript/consistent-generic-constructors': 'error',
        'typescript/method-signature-style': ['error', 'property'],
        'typescript/consistent-type-imports': [
            'error',
            {
                prefer: 'type-imports',
                fixStyle: 'inline-type-imports',
                disallowTypeAnnotations: true,
            },
        ],
        'typescript/no-redeclare': 'error',

        'no-console': 'warn',
        'no-unused-expressions': 'error',
        'no-unused-labels': 'error',
        'no-useless-rename': 'error',
        'object-shorthand': 'error',
        curly: ['error', 'all'],
        eqeqeq: ['error', 'always', { null: 'ignore' }],
        'array-callback-return': 'error',
        'no-self-compare': 'error',
        'no-template-curly-in-string': 'error',
        'default-case-last': 'error',
        'dot-notation': 'error',
        'no-alert': 'error',
        'no-else-return': 'error',
        'no-eval': 'warn',
        'no-lonely-if': 'error',
        'no-multi-assign': 'error',
        'no-multi-str': 'error',
        'no-param-reassign': 'error',
        'no-return-assign': 'error',
        'no-script-url': 'error',
        'no-sequences': 'error',
        'no-throw-literal': 'error',
        'no-unneeded-ternary': 'error',
        'no-useless-call': 'error',
        'no-useless-constructor': 'error',
        'no-useless-return': 'error',
        'operator-assignment': ['error', 'always'],
        'prefer-exponentiation-operator': 'error',
        'prefer-object-has-own': 'error',
        'prefer-promise-reject-errors': 'error',
        'prefer-object-spread': 'error',
        'prefer-template': 'error',
        yoda: 'error',
        radix: 'error',
        'prefer-const': 'error',
        'no-shadow': 'error',
        'block-scoped-var': 'error',
        'arrow-body-style': ['error', 'as-needed'],
        'prefer-arrow-callback': ['error', { allowNamedFunctions: false }],

        'react/exhaustive-deps': 'error',
        'react/set-state-in-effect': 'error',
        'react/jsx-boolean-value': 'error',
        'react/jsx-curly-brace-presence': [
            'error',
            {
                props: 'never',
                children: 'never',
                propElementValues: 'always',
            },
        ],
        'react/jsx-fragments': ['error', 'syntax'],
        'react/jsx-no-comment-textnodes': 'error',
        'react/jsx-no-duplicate-props': 'error',
        'react/jsx-no-target-blank': 'error',
        'react/no-children-prop': 'error',
        'react/no-find-dom-node': 'error',
        'react/no-string-refs': 'error',
        'react/self-closing-comp': 'error',
        'react/void-dom-elements-no-children': 'error',

        'vitest/require-mock-type-parameters': 'off',
    },
    overrides: [
        {
            files: ['**/*.test.ts', '**/*.test.tsx', '**/__mocks__/*.ts', '**/__mocks__/*.tsx'],
            rules: {
                'typescript/no-explicit-any': 'off',
                'react/display-name': 'off',
                'no-console': 'off',
                'vitest/no-hooks': 'off',
                'vitest/prefer-expect-assertions': 'off',
                'vitest/prefer-importing-vitest-globals': 'off',
                'vitest/prefer-describe-function-title': 'off',
                'vitest/require-mock-type-parameters': 'off',
                'vitest/max-expects': ['error', { max: 9 }],
                'vitest/require-hook': ['error', { allowedFunctionCalls: ['mockEnv', 'mockWindow'] }],
            },
        },
    ],
});
