import React from 'react';

import pwaAssets from './pwa-assets.json';

/** PWA tags generated by `pnpm assets`. */
export function PwaHead(): React.JSX.Element {
    return (
        <>
            {pwaAssets.links.map(({ href, rel, sizes, type }) => (
                <link
                    key={`${rel}:${href}`}
                    rel={rel}
                    href={href}
                    sizes={sizes ?? undefined}
                    type={type ?? undefined}
                />
            ))}
            {pwaAssets.metas.map(({ content, name }) => (
                <meta key={name} name={name} content={content} />
            ))}
            {pwaAssets.splashScreens.map(({ href, media }) => (
                <link key={href} rel="apple-touch-startup-image" href={href} media={media} />
            ))}
        </>
    );
}
